
INSERT INTO public.trivia_questions_v2 (category, difficulty, question, answers, correct_index, is_active) VALUES
-- Cartoon questions
('Cartoon', 'easy', 'What is the name of SpongeBob''s best friend?', '["Squidward", "Patrick", "Sandy", "Mr. Krabs"]', 1, true),
('Cartoon', 'easy', 'What color is Scooby-Doo?', '["Black", "Brown", "Gray", "Golden"]', 1, true),
('Cartoon', 'easy', 'Who lives in a pineapple under the sea?', '["Patrick Star", "SpongeBob SquarePants", "Squidward", "Sandy Cheeks"]', 1, true),
('Cartoon', 'easy', 'What animal is Peppa Pig?', '["Cow", "Sheep", "Pig", "Horse"]', 2, true),
('Cartoon', 'easy', 'What is the name of Mickey Mouse''s dog?', '["Goofy", "Pluto", "Donald", "Chip"]', 1, true),
('Cartoon', 'easy', 'Which cartoon features a boy with a football-shaped head?', '["Rugrats", "Hey Arnold!", "Doug", "Recess"]', 1, true),
('Cartoon', 'medium', 'What is the name of Dexter''s sister in Dexter''s Laboratory?', '["Dee Dee", "Daisy", "Dolly", "Diana"]', 0, true),
('Cartoon', 'medium', 'In Avatar: The Last Airbender, what element does Aang bend first?', '["Water", "Earth", "Fire", "Air"]', 3, true),
('Cartoon', 'medium', 'What is the Powerpuff Girls'' home city called?', '["Megaville", "Townsville", "Citysburg", "Metro City"]', 1, true),
('Cartoon', 'medium', 'Who is the villain in Samurai Jack?', '["Him", "Mojo Jojo", "Aku", "Slade"]', 2, true),
('Cartoon', 'medium', 'What year did the original Tom and Jerry cartoon first air?', '["1935", "1940", "1945", "1950"]', 1, true),
('Cartoon', 'medium', 'In The Fairly OddParents, what are Timmy''s fairy godparents'' names?', '["Cosmo and Wanda", "Chip and Dale", "Flora and Fauna", "Star and Moon"]', 0, true),
('Cartoon', 'hard', 'What is the name of the dragon in Dragon Ball that grants wishes?', '["Porunga", "Shenron", "Omega", "Ryujin"]', 1, true),
('Cartoon', 'hard', 'In Gravity Falls, what is Grunkle Stan''s real first name?', '["Stanley", "Stanford", "Steven", "Samuel"]', 0, true),
('Cartoon', 'hard', 'Which studio created the cartoon Courage the Cowardly Dog?', '["Hanna-Barbera", "Cartoon Network Studios", "Stretch Films", "Nickelodeon Animation"]', 2, true),
('Cartoon', 'hard', 'What is the name of the planet the Gems are from in Steven Universe?', '["Gemworld", "Homeworld", "Crystal Planet", "Diamond World"]', 1, true),
('Cartoon', 'hard', 'In Batman: The Animated Series, who voiced the Joker?', '["Kevin Conroy", "Mark Hamill", "Tim Curry", "John DiMaggio"]', 1, true),
('Cartoon', 'hard', 'What year did the original Looney Tunes shorts first premiere?', '["1928", "1930", "1933", "1936"]', 1, true),

-- Toys questions
('Toys', 'easy', 'What shape is a Rubik''s Cube?', '["Sphere", "Cube", "Pyramid", "Cylinder"]', 1, true),
('Toys', 'easy', 'What toy is known for its red and yellow car?', '["Hot Wheels", "Cozy Coupe", "Matchbox", "Tonka"]', 1, true),
('Toys', 'easy', 'What are LEGO bricks made of?', '["Wood", "Metal", "Plastic", "Rubber"]', 2, true),
('Toys', 'easy', 'What toy has a pull string and says phrases?', '["Teddy Ruxpin", "Talking Elmo", "Chatty Cathy", "Furby"]', 2, true),
('Toys', 'easy', 'What is the name of the potato-shaped toy with removable parts?', '["Mr. Potato Head", "Spud Man", "Tater Tot", "Potato Pete"]', 0, true),
('Toys', 'easy', 'What toy lets you draw and then erase by shaking?', '["Magna Doodle", "Etch A Sketch", "Lite-Brite", "Spirograph"]', 1, true),
('Toys', 'medium', 'What year was the first Barbie doll released?', '["1955", "1959", "1962", "1965"]', 1, true),
('Toys', 'medium', 'What was the original name of the toy now known as Play-Doh?', '["Fun Dough", "Wallpaper Cleaner", "Kid Clay", "Sculpt Stuff"]', 1, true),
('Toys', 'medium', 'In what country was LEGO founded?', '["Sweden", "Norway", "Denmark", "Finland"]', 2, true),
('Toys', 'medium', 'What electronic pet toy was hugely popular in the late 1990s?', '["Digimon", "Tamagotchi", "Furby", "Neopets"]', 1, true),
('Toys', 'medium', 'What toy brand is known for its transforming robots?', '["Go-Bots", "Voltron", "Transformers", "Gundam"]', 2, true),
('Toys', 'medium', 'What is the best-selling toy of all time?', '["Barbie", "Hot Wheels", "Rubik''s Cube", "LEGO"]', 2, true),
('Toys', 'hard', 'What year was the first Hot Wheels car released?', '["1965", "1968", "1970", "1972"]', 1, true),
('Toys', 'hard', 'What was the first LEGO minifigure theme?', '["Castle", "Space", "Town", "Pirates"]', 2, true),
('Toys', 'hard', 'What company originally manufactured G.I. Joe?', '["Mattel", "Hasbro", "Kenner", "Tyco"]', 1, true),
('Toys', 'hard', 'In what year was the Furby first released?', '["1996", "1998", "2000", "2002"]', 1, true),
('Toys', 'hard', 'What is the rarest Beanie Baby?', '["Princess Bear", "Peanut the Elephant", "Valentino Bear", "Large Wallace"]', 0, true),
('Toys', 'hard', 'What toy was invented by Hungarian architect Ernő Rubik?', '["Rubik''s Cube", "Tangram", "Simon", "Jenga"]', 0, true);
