
-- Insert Science trivia questions
INSERT INTO public.trivia_questions_v2 (category, difficulty, question, answers, correct_index, is_active) VALUES
('Science', 'easy', 'What planet is known as the Red Planet?', '["Venus", "Mars", "Jupiter", "Saturn"]', 1, true),
('Science', 'easy', 'What is the chemical symbol for water?', '["H2O", "CO2", "O2", "NaCl"]', 0, true),
('Science', 'easy', 'How many planets are in our solar system?', '["7", "8", "9", "10"]', 1, true),
('Science', 'easy', 'What gas do plants absorb from the atmosphere?', '["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"]', 2, true),
('Science', 'easy', 'What is the largest organ in the human body?', '["Heart", "Liver", "Brain", "Skin"]', 3, true),
('Science', 'easy', 'What force keeps us on the ground?', '["Magnetism", "Friction", "Gravity", "Inertia"]', 2, true),
('Science', 'medium', 'What is the speed of light in km/s (approximately)?', '["150,000", "300,000", "450,000", "600,000"]', 1, true),
('Science', 'medium', 'What element has the atomic number 79?', '["Silver", "Gold", "Platinum", "Copper"]', 1, true),
('Science', 'medium', 'What is the powerhouse of the cell?', '["Nucleus", "Ribosome", "Mitochondria", "Golgi Apparatus"]', 2, true),
('Science', 'medium', 'Which planet has the most moons?', '["Jupiter", "Saturn", "Uranus", "Neptune"]', 1, true),
('Science', 'medium', 'What type of rock is formed from cooled lava?', '["Sedimentary", "Metamorphic", "Igneous", "Limestone"]', 2, true),
('Science', 'medium', 'What is the most abundant gas in Earth''s atmosphere?', '["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"]', 2, true),
('Science', 'hard', 'What is the half-life of Carbon-14 (approximately)?', '["1,000 years", "5,730 years", "10,000 years", "50,000 years"]', 1, true),
('Science', 'hard', 'What particle is responsible for carrying the electromagnetic force?', '["Gluon", "Photon", "W Boson", "Graviton"]', 1, true),
('Science', 'hard', 'What is the Chandrasekhar limit (approximately)?', '["0.5 solar masses", "1.4 solar masses", "3.0 solar masses", "5.0 solar masses"]', 1, true),
('Science', 'hard', 'Which enzyme unwinds DNA during replication?', '["DNA Polymerase", "Ligase", "Helicase", "Primase"]', 2, true),
('Science', 'hard', 'What is the approximate age of the universe?', '["10.8 billion years", "13.8 billion years", "15.2 billion years", "18.6 billion years"]', 1, true),
('Science', 'hard', 'What is Planck''s constant (approximately)?', '["6.626 × 10⁻³⁴ J·s", "3.14 × 10⁻³⁴ J·s", "9.81 × 10⁻³⁴ J·s", "1.602 × 10⁻³⁴ J·s"]', 0, true),

-- Insert Sports trivia questions
('Sports', 'easy', 'How many players are on a basketball team on the court?', '["4", "5", "6", "7"]', 1, true),
('Sports', 'easy', 'In which sport do you use a racket to hit a shuttlecock?', '["Tennis", "Badminton", "Squash", "Table Tennis"]', 1, true),
('Sports', 'easy', 'How many points is a touchdown worth in American football?', '["3", "5", "6", "7"]', 2, true),
('Sports', 'easy', 'What sport is known as "the beautiful game"?', '["Basketball", "Cricket", "Soccer/Football", "Tennis"]', 2, true),
('Sports', 'easy', 'How many rings are on the Olympic flag?', '["3", "4", "5", "6"]', 2, true),
('Sports', 'easy', 'In which sport would you perform a slam dunk?', '["Volleyball", "Basketball", "Tennis", "Baseball"]', 1, true),
('Sports', 'medium', 'Which country has won the most FIFA World Cup titles?', '["Germany", "Argentina", "Italy", "Brazil"]', 3, true),
('Sports', 'medium', 'What is the diameter of a basketball hoop in inches?', '["16", "18", "20", "22"]', 1, true),
('Sports', 'medium', 'Who holds the record for most Olympic gold medals?', '["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"]', 1, true),
('Sports', 'medium', 'In tennis, what is a score of 40-40 called?', '["Match Point", "Deuce", "Advantage", "Break Point"]', 1, true),
('Sports', 'medium', 'How many Grand Slam tournaments are there in tennis?', '["3", "4", "5", "6"]', 1, true),
('Sports', 'medium', 'Which NFL team has won the most Super Bowls?', '["Dallas Cowboys", "San Francisco 49ers", "New England Patriots", "Pittsburgh Steelers"]', 2, true),
('Sports', 'hard', 'What year were the first modern Olympic Games held?', '["1892", "1896", "1900", "1904"]', 1, true),
('Sports', 'hard', 'In cricket, how many balls are in a standard over?', '["4", "5", "6", "8"]', 2, true),
('Sports', 'hard', 'Who was the first player to score 100 points in a single NBA game?', '["Michael Jordan", "Kobe Bryant", "Wilt Chamberlain", "LeBron James"]', 2, true),
('Sports', 'hard', 'What is the length of a marathon in miles (approximately)?', '["24.2", "25.2", "26.2", "27.2"]', 2, true),
('Sports', 'hard', 'Which boxer was known as "The Greatest"?', '["Mike Tyson", "Muhammad Ali", "Sugar Ray Leonard", "Floyd Mayweather"]', 1, true),
('Sports', 'hard', 'In what year did the Premier League begin?', '["1990", "1991", "1992", "1993"]', 2, true);
