// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ennfuoqsmnzwvoloadaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubmZ1b3FzbW56d3ZvbG9hZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzQ2NzAsImV4cCI6MjA2NTA1MDY3MH0.pyPnRlg3jJd6Oyg-mSxf_mChSd6YzpJheiYaxhnccbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);